# Generated by Django 6.0.4 on 2026-05-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('gluten', 'Gluten'), ('crustaceos', 'Crustáceos'), ('huevos', 'Huevos'), ('pescado', 'Pescado'), ('cacahuetes', 'Cacahuetes'), ('soja', 'Soja'), ('leche', 'Leche'), ('frutos_cascara', 'Frutos de cáscara'), ('apio', 'Apio'), ('mostaza', 'Mostaza'), ('sesamo', 'Sésamo'), ('dioxido_azufre', 'Dióxido de azufre'), ('altramuces', 'Altramuces'), ('moluscos', 'Moluscos')], max_length=50, unique=True)),
                ('icono', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Alérgenos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='alergenos',
            field=models.ManyToManyField(blank=True, to='cafeteria.alergeno'),
        ),
    ]
