# Generated by Django 6.0.4 on 2026-05-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_alergeno_producto_alergenos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alergeno',
            name='icono',
        ),
    ]
