# Generated by Django 6.0.4 on 2026-05-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_remove_alergeno_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(default='08:45')),
                ('hora_cierre', models.TimeField(default='14:30')),
                ('hora_corte_turno1', models.TimeField(default='10:30')),
                ('hora_inicio_recreo', models.TimeField(default='11:15')),
                ('hora_fin_recreo', models.TimeField(default='11:45')),
            ],
            options={
                'verbose_name': 'Configuración de la cafetería',
                'verbose_name_plural': 'Configuración de la cafetería',
            },
        ),
    ]
