# Generated by Django 6.0.4 on 2026-05-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_configuracioncafeteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncafeteria',
            name='imagen_inicio',
            field=models.ImageField(blank=True, null=True, upload_to='cafeteria/'),
        ),
    ]
